apiVersion: v1
kind: PersistentVolume
metadata:
  name: portfolio-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard   # 👈 match with PVC
  hostPath:
    path: /data/portfolio-pv    # for Kind/Minikube local testing
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portfolio-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard   # 👈 same as PV

