name: CI/CD - Build, Test, and Deploy to Kind

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js for building React app
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run tests
      - name: Run tests
        run: npm test -- --passWithNoTests

      # Step 5: Build React app
      - name: Build app
        run: npm run build

      # Step 6: Create Kind cluster
      - name: Create Kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: portfolio-cluster

      # Step 7: Deploy manifests to Kind
      - name: Deploy to Kind
        run: |
          kubectl create namespace portfolio-ns || true
          kubectl apply -f K8s/ -n portfolio-ns

      # Step 8: Verify deployment
      - name: Verify pods
        run: kubectl get pods -n portfolio-ns
